Feature: Add an activity for dog

    Scenario: Create new application for 2 dogs
        Given I open the url "/"
        When I click on the link containing "Process new CDO or"
        And I set "Logan" to the inputfield "#firstName"
        And I set "Crawley" to the inputfield "#lastName"
        And I click on the element "button=Continue"
        And I set "B1 1HN" to the inputfield "#postcode"
        And I set "29" to the inputfield "#houseNumber"
        And I click on the element "button=Continue"
        And I click on the element "button=Confirm address"
        And I set "345677689622111" to the inputfield "#microchipNumber"
        And I click on the element "button=Continue"
        And I select the radio option with the value "Japanese Tosa" from the radio group "breed"
        And I set "Rudy" to the inputfield "#name"
        And I select the radio option with the value "cdo" from the radio group "applicationType"
        And I set "23" to the inputfield "#cdoIssued-day"
        And I set "09" to the inputfield "#cdoIssued-month"
        And I set "2024" to the inputfield "#cdoIssued-year"
        And I click on the element "button=Add dog details"
        And I click on the element "button=Add another dog for this owner"
        And I set "345645654323322" to the inputfield "#microchipNumber"
        And I click on the element "button=Continue"
        And I select the radio option with the value "Pit Bull Terrier" from the radio group "breed"
        And I set "Yoyo" to the inputfield "#name"
        And I select the radio option with the value "cdo" from the radio group "applicationType"
        And I set "22" to the inputfield "#cdoIssued-day"
        And I set "09" to the inputfield "#cdoIssued-month"
        And I set "2024" to the inputfield "#cdoIssued-year"
        And I click on the element "button=Add dog details"
        And I click on the element "button=Confirm details"
        And I set "Northampton (Northampton Crown Court)" to the inputfield "#court"
        And I click on the element "#legislationOfficer"
        And I click on the element "button=Continue"
        And I click on the element "button=Confirm details"
        Then I expect that element "h1" contains the text "Record created"

    Scenario: Search the dog and check history
        When I click on the link "Home"
        And I click on the link "Search dog index"
        And I set "Rudy" to the inputfield "#searchTerms"
        And I press "Enter"
        And I click on the link containing "ED30"
        And I click on the link "Dog record"
        And I click on the link "Check history"
        Then I expect that element "tbody" contains the text "Dog record created (Applying for exemption)"

    Scenario: Add an activity to the dog(We've sent something)
        When I open the url "/"
        And I click on the link "Search dog index"
        And I set "Rudy" to the inputfield "#searchTerms"
        And I press "Enter"
        And I click on the link containing "ED30"
        And I click on the link "Dog record"
        And I click on the link "Add an activity"
        And I select the radio option with the value "sent" from the radio group "activityType"
        And I click on the element "button=Continue"
        And I select the radio option with the value "12" from the radio group "activity"
        And I click on the element "button=Continue"
        Then I expect that element "h1" contains the text "Reminder to owner"
        
    Scenario: Check the history to the dog(We've sent something)
        When I open the url "/"
        And I click on the link "Search dog index"
        And I set "Rudy" to the inputfield "#searchTerms"
        And I press "Enter"
        And I click on the link containing "ED30"
        And I click on the link "Dog record"
        And I click on the link "Check history"
        Then I expect that element "tbody" contains the text "Reminder to owner sent"

    Scenario: Add an activity to the dog(We've received something)
        When I open the url "/"
        And I click on the link "Search dog index"
        And I set "Rudy" to the inputfield "#searchTerms"
        And I press "Enter"
        And I click on the link containing "ED30"
        And I click on the link "Dog record"        
        And I click on the link "Add an activity"
        And I select the radio option with the value "received" from the radio group "activityType"
        And I click on the element "button=Continue"
        And I select the radio option with the value "15" from the radio group "activity"
        And I click on the element "button=Continue"
        Then I expect that element "h1" contains the text "Corrected CDO"

    Scenario: Check the history to the dog(We've received something)
        When I open the url "/"
        And I click on the link "Search dog index"
        And I set "Rudy" to the inputfield "#searchTerms"
        And I press "Enter"
        And I click on the link containing "ED30"
        And I click on the link "Dog record"
        And I click on the link "Check history"
        Then I expect that element "tbody" contains the text "Corrected CDO received"