Feature: Add new dog to the existing owner

    Scenario: Creating a new owner with multiple dogs
        Given I open the url "/"
        When I click on the link containing "Process new CDO or"
        And I set "Natalie" to the inputfield "#firstName"
        And I set "Bernard" to the inputfield "#lastName"
        And I click on the element "button=Continue"
        And I set "ME5 7QU" to the inputfield "#postcode"
        And I set "2" to the inputfield "#houseNumber"
        And I click on the element "button=Continue"
        And I click on the element "button=Confirm address"
        And I set "345643111112345" to the inputfield "#microchipNumber"
        And I click on the element "button=Continue"
        And I select the radio option with the value "XL Bully" from the radio group "breed"
        And I set "Leon" to the inputfield "#name"
        And I select the radio option with the value "cdo" from the radio group "applicationType"
        And I set "01" to the inputfield "#cdoIssued-day"
        And I set "05" to the inputfield "#cdoIssued-month"
        And I set "2024" to the inputfield "#cdoIssued-year"
        And I click on the element "button=Add dog details"
        And I click on the element "button=Add another dog for this owner"
        And I set "345643222222345" to the inputfield "#microchipNumber"
        And I click on the element "button=Continue"
        And I select the radio option with the value "Pit Bull Terrier" from the radio group "breed"
        And I set "Tom" to the inputfield "#name"
        And I select the radio option with the value "cdo" from the radio group "applicationType"
        And I set "30" to the inputfield "#cdoIssued-day"
        And I set "04" to the inputfield "#cdoIssued-month"
        And I set "2024" to the inputfield "#cdoIssued-year"
        And I click on the element "button=Add dog details"
        And I click on the element "button=Confirm details"
        And I set "Northampton (Northampton Crown Court)" to the inputfield "#court"
        And I click on the element "#legislationOfficer"
        And I click on the element "button=Continue"
        And I click on the element "button=Confirm details"
        Then I expect that element "h1" contains the text "Record created" 
        
    Scenario: Add new dog to the existing owner with multiple dogs
        When I click on the link "Dangerous Dogs Index home"
        And I click on the link containing "Process new CDO or"
        And I set "Natalie" to the inputfield "#firstName"
        And I set "Bernard" to the inputfield "#lastName"
        And I click on the element "button=Continue"
        And I select the radio option with the value "0" from the radio group "address"
        And I click on the element "button=Continue"
        And I select the radio option with the value "-1" from the radio group "dog"
        And I click on the element "button=Continue"
        And I set "345645622222345" to the inputfield "#microchipNumber"
        And I click on the element "button=Continue"
        And I select the radio option with the value "Pit Bull Terrier" from the radio group "breed"
        And I set "Yoyo" to the inputfield "#name"
        And I select the radio option with the value "interim-exemption" from the radio group "applicationType"
        And I click on the element "button=Add dog details"       
        And I click on the element "button=Confirm details"
        And I set "Kent Police" to the inputfield "#court"
        And I set "David" to the inputfield "#legislationOfficer"
        And I click on the element "button=Continue"
        And I click on the element "button=Confirm details"
        Then I expect that element "h1" contains the text "Record created" 