Feature: Change address or Country of an owner

    Scenario: Create new application with 2 dogs
        Given I open the url "/"
        When I click on the link containing "Process new CDO or"
        And I set "Sean" to the inputfield "#firstName"
        And I set "Steel" to the inputfield "#lastName"
        And I click on the element "button=Continue"
        And I set "B1 1HN" to the inputfield "#postcode"
        And I set "29" to the inputfield "#houseNumber"
        And I click on the element "button=Continue"
        And I click on the element "button=Confirm address"
        And I set "345670987633333" to the inputfield "#microchipNumber"
        And I click on the element "button=Continue"
        And I select the radio option with the value "Japanese Tosa" from the radio group "breed"
        And I set "Lola" to the inputfield "#name"
        And I select the radio option with the value "cdo" from the radio group "applicationType"
        And I set "23" to the inputfield "#cdoIssued-day"
        And I set "09" to the inputfield "#cdoIssued-month"
        And I set "2024" to the inputfield "#cdoIssued-year"
        And I click on the element "button=Add dog details"
        And I click on the element "button=Add another dog for this owner"
        And I set "345670987644444" to the inputfield "#microchipNumber"
        And I click on the element "button=Continue"
        And I select the radio option with the value "Pit Bull Terrier" from the radio group "breed"
        And I set "Luna" to the inputfield "#name"
        And I select the radio option with the value "cdo" from the radio group "applicationType"
        And I set "22" to the inputfield "#cdoIssued-day"
        And I set "09" to the inputfield "#cdoIssued-month"
        And I set "2024" to the inputfield "#cdoIssued-year"
        And I click on the element "button=Add dog details"
        And I click on the element "button=Confirm details"
        And I set "Northampton (Northampton Crown Court)" to the inputfield "#court"
        And I click on the element "#legislationOfficer"
        And I click on the element "button=Continue"
        And I click on the element "button=Confirm details"
        Then I expect that element "h1" contains the text "Record created"

    Scenario: Change from Northampton(England) address to Cardiff(Wales) address through edit owner details page
        Given I open the url "/"
        When I click on the link "Search dog index"
        And I set "Sean Steel" to the inputfield "#searchTerms"
        And I select the radio option with the value "owner" from the radio group "searchType"
        And I click on the element "button=Search"
        And I click on the link containing "Sean Steel"
        And I click on the link containing "Edit details"
        And I set "6 HEATH MEAD" to the inputfield "#addressLine1"
        And I set "CANTON" to the inputfield "#addressLine2"
        And I set "CARDIFF" to the inputfield "#town"
        And I set "CF14 3PJ" to the inputfield "#postcode"
        And I select the option with the value "Wales" for element "#country"
        And I click on the element "button=Save details"
        Then I expect that element "h1" contains the text "The police force for the dog records has changed"
        And I expect that element "form" contains the text "The police force is now South Wales Police."

    Scenario: Verify address is updated
        Given I open the url "/"
        When I click on the link "Search dog index"
        And I set "Sean Steel" to the inputfield "#searchTerms"
        And I select the radio option with the value "owner" from the radio group "searchType"
        And I click on the element "button=Search"
        And I click on the link containing "Sean Steel"
        Then I expect that element "h1" contains the text "Sean Steel"
        And I expect that element "(//dd)[1]" contains the text "Sean Steel"
        And I expect that element "(//dd)[3]" contains the text "6 HEATH MEAD"
        And I expect that element "(//dd)[3]" contains the text "CANTON"
        And I expect that element "(//dd)[3]" contains the text "CARDIFF" 
        And I expect that element "(//dd)[3]" contains the text "CF14 3PJ"
        And I expect that element "(//dd)[7]" contains the text "Wales"

    Scenario: Verify police force is updated (Dog1 of 2)
        Given I open the url "/"
        When I click on the link "Search dog index"
        And I set "Lola" to the inputfield "#searchTerms"
        And I press "Enter"
        And I click on the link containing "ED30"
        And I click on the link "Dog record"
        Then I expect that element "(//dd)[20]" contains the text "South Wales Police"

    Scenario: Verify police force is updated (Dog2 of 2)
        Given I open the url "/"
        When I click on the link "Search dog index"
        And I set "Luna" to the inputfield "#searchTerms"
        And I press "Enter"
        And I click on the link containing "ED30"
        And I click on the link "Dog record"
        Then I expect that element "(//dd)[20]" contains the text "South Wales Police"

    Scenario: Change from Cardiff(Wales) to Leeds(England) address through postcode lookup
        Given I open the url "/"
        When I click on the link "Search dog index"
        And I set "Sean Steel" to the inputfield "#searchTerms"
        And I select the radio option with the value "owner" from the radio group "searchType"
        And I click on the element "button=Search"
        And I click on the link containing "Sean Steel"
        And I click on the link containing "Change"  
        And I set "LS20 8DA" to the inputfield "#postcode"
        And I set "12" to the inputfield "#houseNumber"
        And I click on the element "button=Continue"
        And I click on the element "button=Confirm address"
        Then I expect that element "h1" contains the text "The police force for the dog records has changed"
        And I expect that element "form" contains the text "The police force is now West Yorkshire Police."
   
    Scenario: Verify address is updated
        Given I open the url "/"
        When I click on the link "Search dog index"
        And I set "Sean Steel" to the inputfield "#searchTerms"
        And I select the radio option with the value "owner" from the radio group "searchType"
        And I click on the element "button=Search"
        And I click on the link containing "Sean Steel"
        Then I expect that element "h1" contains the text "Sean Steel"
        And I expect that element "(//dd)[1]" contains the text "Sean Steel"
        And I expect that element "(//dd)[3]" contains the text "12 Ings Lane"
        And I expect that element "(//dd)[3]" contains the text "Guiseley"
        And I expect that element "(//dd)[3]" contains the text "Leeds" 
        And I expect that element "(//dd)[3]" contains the text "S20 8DA"
        And I expect that element "(//dd)[7]" contains the text "England"

    Scenario: Verify police force is updated (Dog1 of 2)
        Given I open the url "/"
        When I click on the link "Search dog index"
        And I set "Lola" to the inputfield "#searchTerms"
        And I press "Enter"
        And I click on the link containing "ED30"
        And I click on the link "Dog record"
        Then I expect that element "(//dd)[20]" contains the text "West Yorkshire Police"

    Scenario: Verify police force is updated (Dog2 of 2)
        Given I open the url "/"
        When I click on the link "Search dog index"
        And I set "Luna" to the inputfield "#searchTerms"
        And I press "Enter"
        And I click on the link containing "ED30"
        And I click on the link "Dog record"
        Then I expect that element "(//dd)[20]" contains the text "West Yorkshire Police"

    Scenario: Change Leeds(England) to Bristol(England) address through enter address manually
        Given I open the url "/"
        When I click on the link "Search dog index"
        And I set "Sean Steel" to the inputfield "#searchTerms"
        And I select the radio option with the value "owner" from the radio group "searchType"
        And I click on the element "button=Search"
        And I click on the link containing "Sean Steel"
        And I click on the link containing "Change"  
        And I click on the link containing "Enter address manually"    
        And I set "Flat 14, 1a, Marsh Street" to the inputfield "#addressLine1"
        And I set "Bristol" to the inputfield "#town"
        And I set "BS1 1RT" to the inputfield "#postcode"
        And I click on the element "button=Save address"
        Then I expect that element "h1" contains the text "The police force for the dog records has changed"
        And I expect that element "form" contains the text "The police force is now Avon and Somerset Constabulary."

    Scenario: Verify address is updated
        Given I open the url "/"
        When I click on the link "Search dog index"
        And I set "Sean Steel" to the inputfield "#searchTerms"
        And I select the radio option with the value "owner" from the radio group "searchType"
        And I click on the element "button=Search"
        And I click on the link containing "Sean Steel"
        Then I expect that element "h1" contains the text "Sean Steel"
        And I expect that element "(//dd)[1]" contains the text "Sean Steel"
        And I expect that element "(//dd)[3]" contains the text "Flat 14, 1a, Marsh Street"
        And I expect that element "(//dd)[3]" contains the text "Bristol" 
        And I expect that element "(//dd)[3]" contains the text "BS1 1RT"
        And I expect that element "(//dd)[7]" contains the text "England"

    Scenario: Verify police force is updated (Dog1 of 2)
        Given I open the url "/"
        When I click on the link "Search dog index"
        And I set "Lola" to the inputfield "#searchTerms"
        And I press "Enter"
        And I click on the link containing "ED30"
        And I click on the link "Dog record"
        Then I expect that element "(//dd)[20]" contains the text "Avon and Somerset Constabulary"

    Scenario: Verify police force is updated (Dog2 of 2)
        Given I open the url "/"
        When I click on the link "Search dog index"
        And I set "Luna" to the inputfield "#searchTerms"
        And I press "Enter"
        And I click on the link containing "ED30"
        And I click on the link "Dog record"
        Then I expect that element "(//dd)[20]" contains the text "Avon and Somerset Constabulary"

    Scenario: Change from Bristol(England) address to Northampton(England) address through edit owner details page with invalid postcode
        Given I open the url "/"
        When I click on the link "Search dog index"
        And I set "Sean Steel" to the inputfield "#searchTerms"
        And I select the radio option with the value "owner" from the radio group "searchType"
        And I click on the element "button=Search"
        And I click on the link containing "Sean Steel"
        And I click on the link containing "Edit details"
        And I set "Flat 7, 23" to the inputfield "#addressLine1"
        And I set "Henry Bird Way" to the inputfield "#addressLine2"
        And I set "Northampton" to the inputfield "#town"
        And I set "NN11 7DF" to the inputfield "#postcode"
        And I click on the element "button=Save details"
        Then I expect that element "h1" contains the text "Check if the police force also needs to change"
        And I expect that element "form" contains the text "The police force is currently Avon and Somerset Constabulary."
        And I expect that element "form" contains the text "The owner address changed to:"
        And I expect that element "form" contains the text "NN11 7DF"

    Scenario: Verify address is updated
        Given I open the url "/"
        When I click on the link "Search dog index"
        And I set "Sean Steel" to the inputfield "#searchTerms"
        And I select the radio option with the value "owner" from the radio group "searchType"
        And I click on the element "button=Search"
        And I click on the link containing "Sean Steel"
        Then I expect that element "h1" contains the text "Sean Steel"
        And I expect that element "(//dd)[1]" contains the text "Sean Steel"
        And I expect that element "(//dd)[3]" contains the text "Flat 7, 23"
        And I expect that element "(//dd)[3]" contains the text "Northampton" 
        And I expect that element "(//dd)[3]" contains the text "NN11 7DF"
        And I expect that element "(//dd)[7]" contains the text "England"

    Scenario: Verify police force is not updated (Dog1 of 2)
        Given I open the url "/"
        When I click on the link "Search dog index"
        And I set "Lola" to the inputfield "#searchTerms"
        And I press "Enter"
        And I click on the link containing "ED30"
        And I click on the link "Dog record"
        Then I expect that element "(//dd)[20]" contains the text "Avon and Somerset Constabulary"

    Scenario: Verify police force is not updated (Dog2 of 2)
        Given I open the url "/"
        When I click on the link "Search dog index"
        And I set "Luna" to the inputfield "#searchTerms"
        And I press "Enter"
        And I click on the link containing "ED30"
        And I click on the link "Dog record"
        Then I expect that element "(//dd)[20]" contains the text "Avon and Somerset Constabulary"     