Feature: Change address or Country of an owner

    Scenario: Create new application with 2 dogs
        Given I open the url "/"
        When I click on the link containing "Process new CDO or"
        And I set "Paul" to the inputfield "#firstName"
        And I set "Steel" to the inputfield "#lastName"
        And I click on the element "button=Continue"
        And I set "B1 1HN" to the inputfield "#postcode"
        And I set "29" to the inputfield "#houseNumber"
        And I click on the element "button=Continue"
        And I click on the element "button=Confirm address"
        And I set "345670987622111" to the inputfield "#microchipNumber"
        And I click on the element "button=Continue"
        And I select the radio option with the value "Japanese Tosa" from the radio group "breed"
        And I set "Max" to the inputfield "#name"
        And I select the radio option with the value "cdo" from the radio group "applicationType"
        And I set "23" to the inputfield "#cdoIssued-day"
        And I set "09" to the inputfield "#cdoIssued-month"
        And I set "2024" to the inputfield "#cdoIssued-year"
        And I click on the element "button=Add dog details"
        And I click on the element "button=Add another dog for this owner"
        And I set "345670987622222" to the inputfield "#microchipNumber"
        And I click on the element "button=Continue"
        And I select the radio option with the value "Pit Bull Terrier" from the radio group "breed"
        And I set "Ollie" to the inputfield "#name"
        And I select the radio option with the value "cdo" from the radio group "applicationType"
        And I set "22" to the inputfield "#cdoIssued-day"
        And I set "09" to the inputfield "#cdoIssued-month"
        And I set "2024" to the inputfield "#cdoIssued-year"
        And I click on the element "button=Add dog details"
        And I click on the element "button=Confirm details"
        And I set "Northampton (Northampton Crown Court)" to the inputfield "#court"
        And I click on the element "#legislationOfficer"
        And I click on the element "button=Continue"
        And I click on the element "button=Confirm details"
        Then I expect that element "h1" contains the text "Record created"

    Scenario: Change from Birmingham(England) address to Glasgow(Scotland) address through postcode lookup
        Given I open the url "/"
        When I click on the link "Search dog index"
        And I set "Paul Steel" to the inputfield "#searchTerms"
        And I click on the element "button=Search"
        And I click on the link containing "Paul Steel"
        And I click on the link containing "Change"
        And I set "G1 1SS" to the inputfield "#postcode"
        And I set "8" to the inputfield "#houseNumber"
        And I click on the element "button=Continue"
        And I click on the element "button=Confirm address"
        Then I expect that element "h1" contains the text "The owner’s country is now Scotland"
        And I expect that element "form" contains the text "The police force is now Police Scotland."

    Scenario: Check update dog status instructions page
        When I click on the element "button=Continue"
        Then I expect that element "h1" contains the text "Update the dog status"

    Scenario: Verify address is updated
        Given I open the url "/"
        When I click on the link "Search dog index"
        And I set "Paul Steel" to the inputfield "#searchTerms"
        And I click on the element "button=Search"
        And I click on the link containing "Paul Steel"
        Then I expect that element "h1" contains the text "Paul Steel"
        And I expect that element "(//dd)[1]" contains the text "Paul Steel"
        And I expect that element "(//dd)[3]" contains the text "8 Wilson Street"
        And I expect that element "(//dd)[3]" contains the text "Glasgow" 
        And I expect that element "(//dd)[3]" contains the text "G1 1SS"
        And I expect that element "(//dd)[7]" contains the text "Scotland"

    Scenario: Verify police force is updated (Dog1 of 2)
        Given I open the url "/"
        When I click on the link "Search dog index"
        And I set "Max" to the inputfield "#searchTerms"
        And I press "Enter"
        And I click on the link containing "ED30"
        And I click on the link "Dog record"
        Then I expect that element "(//dd)[21]" contains the text "Police Scotland"

    Scenario: Verify police force is updated (Dog2 of 2)
        Given I open the url "/"
        When I click on the link "Search dog index"
        And I set "Ollie" to the inputfield "#searchTerms"
        And I press "Enter"
        And I click on the link containing "ED30"
        And I click on the link "Dog record"
        Then I expect that element "(//dd)[21]" contains the text "Police Scotland"
    
    Scenario: Change from Glasgow(Scotland) address to Cardiff(Wales) address through edit owner details page
        Given I open the url "/"
        When I click on the link "Search dog index"
        And I set "Paul Steel" to the inputfield "#searchTerms"
        And I click on the element "button=Search"
        And I click on the link containing "Paul Steel"
        And I click on the link containing "Edit details"
        And I set "6 HEATH MEAD" to the inputfield "#addressLine1"
        And I set "CANTON" to the inputfield "#addressLine2"
        And I set "CARDIFF" to the inputfield "#town"
        And I set "CF14 3PJ" to the inputfield "#postcode"
        And I select the option with the value "Wales" for element "#country"
        And I click on the element "button=Save details"
        Then I expect that element "h1" contains the text "The owner’s country is now Wales"
        And I expect that element "form" contains the text "The police force is now South Wales Police."

    Scenario: Check update dog status instructions page
        When I click on the element "button=Continue"
        Then I expect that element "h1" contains the text "Update the dog status"

    Scenario: Verify address is updated
        Given I open the url "/"
        When I click on the link "Search dog index"
        And I set "Paul Steel" to the inputfield "#searchTerms"
        And I click on the element "button=Search"
        And I click on the link containing "Paul Steel"
        Then I expect that element "h1" contains the text "Paul Steel"
        And I expect that element "(//dd)[1]" contains the text "Paul Steel"
        And I expect that element "(//dd)[3]" contains the text "6 HEATH MEAD"
        And I expect that element "(//dd)[3]" contains the text "CARDIFF" 
        And I expect that element "(//dd)[3]" contains the text "CF14 3PJ"
        And I expect that element "(//dd)[7]" contains the text "Wales"

    Scenario: Verify police force is updated (Dog1 of 2)
        Given I open the url "/"
        When I click on the link "Search dog index"
        And I set "Max" to the inputfield "#searchTerms"
        And I press "Enter"
        And I click on the link containing "ED30"
        And I click on the link "Dog record"
        Then I expect that element "(//dd)[21]" contains the text "South Wales Police"

    Scenario: Verify police force is updated (Dog2 of 2)
        Given I open the url "/"
        When I click on the link "Search dog index"
        And I set "Ollie" to the inputfield "#searchTerms"
        And I press "Enter"
        And I click on the link containing "ED30"
        And I click on the link "Dog record"
        Then I expect that element "(//dd)[21]" contains the text "South Wales Police"
    
    Scenario: Change from Cardiff(Wales) address to Perth(Scotland) address through enter address manually
        Given I open the url "/"
        When I click on the link "Search dog index"
        And I set "Paul Steel" to the inputfield "#searchTerms"
        And I click on the element "button=Search"
        And I click on the link containing "Paul Steel"
        And I click on the link containing "Change"
        And I click on the link containing "Enter address manually"    
        And I set "125" to the inputfield "#addressLine1"
        And I set "Burchard Crescent" to the inputfield "#addressLine2"
        And I set "Perth" to the inputfield "#town"
        And I set "PH1 1DR" to the inputfield "#postcode"
        And I select the option with the value "Scotland" for element "#country"
        And I click on the element "button=Save address"
        Then I expect that element "h1" contains the text "The owner’s country is now Scotland"
        And I expect that element "form" contains the text "The police force is now Police Scotland."

    Scenario: Check update dog status instructions page
        When I click on the element "button=Continue"
        Then I expect that element "h1" contains the text "Update the dog status"

    Scenario: Verify address is updated
        Given I open the url "/"
        When I click on the link "Search dog index"
        And I set "Paul Steel" to the inputfield "#searchTerms"
        And I click on the element "button=Search"
        And I click on the link containing "Paul Steel"
        Then I expect that element "h1" contains the text "Paul Steel"
        And I expect that element "(//dd)[1]" contains the text "Paul Steel"
        And I expect that element "(//dd)[3]" contains the text "125"
        And I expect that element "(//dd)[3]" contains the text "Perth" 
        And I expect that element "(//dd)[3]" contains the text "PH1 1DR"
        And I expect that element "(//dd)[7]" contains the text "Scotland"

    Scenario: Verify police force is updated (Dog1 of 2)
        Given I open the url "/"
        When I click on the link "Search dog index"
        And I set "Max" to the inputfield "#searchTerms"
        And I press "Enter"
        And I click on the link containing "ED30"
        And I click on the link "Dog record"
        Then I expect that element "(//dd)[21]" contains the text "Police Scotland"

    Scenario: Verify police force is updated (Dog2 of 2)
        Given I open the url "/"
        When I click on the link "Search dog index"
        And I set "Ollie" to the inputfield "#searchTerms"
        And I press "Enter"
        And I click on the link containing "ED30"
        And I click on the link "Dog record"
        Then I expect that element "(//dd)[21]" contains the text "Police Scotland"

    Scenario: Change country from Scotland to England through edit owner details page(Invalid postcode)
        Given I open the url "/"
        When I click on the link "Search dog index"
        And I set "Paul Steel" to the inputfield "#searchTerms"
        And I click on the element "button=Search"
        And I click on the link containing "Paul Steel"
        And I click on the link containing "Edit details"
        And I set "CV22 3SE" to the inputfield "#postcode"
        And I select the option with the value "England" for element "#country"
        And I click on the element "button=Save details"
        Then I expect that element "h1" contains the text "The owner’s country is now England"

    Scenario: Check update dog status instructions page
        When I click on the element "button=Continue"
        Then I expect that element "h1" contains the text "Check if the police force also needs to change"
        And I expect that element "form" contains the text "The police force is currently Police Scotland."

    Scenario:
        When I click on the element "button=Continue"
        Then I expect that element "h1" contains the text "Update the dog status"

    Scenario: Verify address is updated
        Given I open the url "/"
        When I click on the link "Search dog index"
        And I set "Paul Steel" to the inputfield "#searchTerms"
        And I click on the element "button=Search"
        And I click on the link containing "Paul Steel"
        Then I expect that element "h1" contains the text "Paul Steel"
        And I expect that element "(//dd)[1]" contains the text "Paul Steel"
        And I expect that element "(//dd)[3]" contains the text "125"
        And I expect that element "(//dd)[3]" contains the text "Perth" 
        And I expect that element "(//dd)[3]" contains the text "CV22 3SE"
        And I expect that element "(//dd)[7]" contains the text "England"

    Scenario: Verify police force is not updated (Dog1 of 2)
        Given I open the url "/"
        When I click on the link "Search dog index"
        And I set "Max" to the inputfield "#searchTerms"
        And I press "Enter"
        And I click on the link containing "ED30"
        And I click on the link "Dog record"
        Then I expect that element "(//dd)[21]" contains the text "Police Scotland"

    Scenario: Verify police force is not updated (Dog2 of 2)
        Given I open the url "/"
        When I click on the link "Search dog index"
        And I set "Ollie" to the inputfield "#searchTerms"
        And I press "Enter"
        And I click on the link containing "ED30"
        And I click on the link "Dog record"
        Then I expect that element "(//dd)[21]" contains the text "Police Scotland"