Feature: Prevent XLBully for Scotland address

    Scenario: Verify error message when processing new cdo application for XL Bully with Scotland address
        Given I open the url "/"
        When I click on the link containing "Process new CDO or"
        And I set "Matt" to the inputfield "#firstName"
        And I set "Richards" to the inputfield "#lastName"
        And I click on the element "button=Continue"
        And I set "EH17 8ZE" to the inputfield "#postcode"
        And I set "23" to the inputfield "#houseNumber"
        And I click on the element "button=Continue"
        And I click on the element "button=Confirm address"
        And I set "456321589632548" to the inputfield "#microchipNumber"
        And I click on the element "button=Continue"
        And I select the radio option with the value "XL Bully" from the radio group "breed"
        And I set "Lucy" to the inputfield "#name"
        And I select the radio option with the value "cdo" from the radio group "applicationType"
        And I set "08" to the inputfield "#cdoIssued-day"
        And I set "08" to the inputfield "#cdoIssued-month"
        And I set "2024" to the inputfield "#cdoIssued-year"
        And I click on the element "button=Add dog details"
        Then I expect that element "form" contains the text "Address for an XL Bully must be in England or Wales"

    Scenario: Verify error message when processing new Interim application for XL Bully with Scotland address
        Given I open the url "/"
        When I click on the link containing "Process new CDO or"
        And I set "Matt" to the inputfield "#firstName"
        And I set "Richards" to the inputfield "#lastName"
        And I click on the element "button=Continue"
        And I set "EH17 8ZE" to the inputfield "#postcode"
        And I set "23" to the inputfield "#houseNumber"
        And I click on the element "button=Continue"
        And I click on the element "button=Confirm address"
        And I set "456321589632548" to the inputfield "#microchipNumber"
        And I click on the element "button=Continue"
        And I select the radio option with the value "XL Bully" from the radio group "breed"
        And I set "Lucy" to the inputfield "#name"
        And I select the radio option with the value "interim-exemption" from the radio group "applicationType"
        And I click on the element "button=Add dog details"
        Then I expect that element "form" contains the text "Address for an XL Bully must be in England or Wales"

    Scenario: Verify error message when changing non XL Bully to XL Bully Scotland address
        Given I open the url "/"
        When I click on the link containing "Process new CDO or"
        And I set "Matt" to the inputfield "#firstName"
        And I set "Richards" to the inputfield "#lastName"
        And I click on the element "button=Continue"
        And I set "EH17 8ZE" to the inputfield "#postcode"
        And I set "23" to the inputfield "#houseNumber"
        And I click on the element "button=Continue"
        And I click on the element "button=Confirm address"
        And I set "556321589632548" to the inputfield "#microchipNumber"
        And I click on the element "button=Continue"
        And I select the radio option with the value "Fila Brasileiro" from the radio group "breed"
        And I set "Lilly" to the inputfield "#name"
        And I select the radio option with the value "cdo" from the radio group "applicationType"
        And I set "08" to the inputfield "#cdoIssued-day"
        And I set "08" to the inputfield "#cdoIssued-month"
        And I set "2024" to the inputfield "#cdoIssued-year"
        And I click on the element "button=Add dog details"
        And I click on the element "button=Confirm details"
        And I select the option with the value "52" for element "#policeForce"
        And I set "Northampton (Northampton Crown Court)" to the inputfield "#court"
        And I click on the element "#legislationOfficer"
        And I click on the element "button=Continue"
        And I click on the element "button=Confirm details"
        And I click on the link containing "ED30"
        And I click on the link containing "Dog record"
        And I click on the element "(//a[contains(text(),'Edit details')])[1]"
        And I select the option with the value "XL Bully" for element "#breed"
        And I click on the element "button=Save details"
        Then I expect that element "form" contains the text "Address for an XL Bully must be in England or Wales"

    Scenario: Verify error message when changing XL Bully owner address from England to Scotland
        Given I open the url "/"
        When I click on the link containing "Process new CDO or"
        And I set "Kelly" to the inputfield "#firstName"
        And I set "Bernard" to the inputfield "#lastName"
        And I click on the element "button=Continue"
        And I set "ME5 7QU" to the inputfield "#postcode"
        And I set "2" to the inputfield "#houseNumber"
        And I click on the element "button=Continue"
        And I click on the element "button=Confirm address"
        And I set "345643111115645" to the inputfield "#microchipNumber"
        And I click on the element "button=Continue"
        And I select the radio option with the value "XL Bully" from the radio group "breed"
        And I set "Sassy" to the inputfield "#name"
        And I select the radio option with the value "cdo" from the radio group "applicationType"
        And I set "01" to the inputfield "#cdoIssued-day"
        And I set "05" to the inputfield "#cdoIssued-month"
        And I set "2024" to the inputfield "#cdoIssued-year"
        And I click on the element "button=Add dog details"
        And I click on the element "button=Confirm details"
        And I set "Northampton (Northampton Crown Court)" to the inputfield "#court"
        And I click on the element "#legislationOfficer"
        And I click on the element "button=Continue"
        And I click on the element "button=Confirm details"
        And I click on the link containing "ED30"
        And I click on the link containing "Owner record"
        And I click on the link containing "Change"
        And I set "EH17 8ZE" to the inputfield "#postcode"
        And I set "23" to the inputfield "#houseNumber"
        And I click on the element "button=Continue"
        And I click on the element "button=Confirm address"
        Then I expect that element "form" contains the text "Address for an XL Bully must be in England or Wales"

    Scenario: Verify error message when changing XL Bully owner Country from England to Scotland
        Given I open the url "/"
        When I click on the link "Search dog index"
        And I set "Kelly" to the inputfield "#searchTerms"
        And I select the radio option with the value "owner" from the radio group "searchType"
        And I click on the element "button=Search"
        And I click on the link containing "Kelly"
        And I click on the link containing "Edit details"
        And I select the option with the value "Scotland" for element "#country"
        And I click on the element "button=Save details"
        Then I expect that element "form" contains the text "Address for an XL Bully must be in England or Wales"