Feature: Update status manually

    Scenario: Add Removed from CDO process(update status from pre-exempt to failed) 
        Given I open the url "/"
        When I click on the link "Search dog index"
        And I set "Bob" to the inputfield "#searchTerms"
        And I press "Enter"
        And I click on the link containing "ED30"
        And I click on the link "Dog record"
        And I click on the element "(//a[contains(text(),'Edit details')])[2]"
        And I set "11" to the inputfield "#nonComplianceLetterSent-day"
        And I set "03" to the inputfield "#nonComplianceLetterSent-month"
        And I set "2024" to the inputfield "#nonComplianceLetterSent-year"
        And I click on the element "button=Save details" 
        Then I expect that element "h1" contains the text "Dog ED30"
        And I expect that element "(//dd)[14]" contains the text "Failed to exempt dog"

    Scenario: Check the activity for dog
        When I click on the link "Check activity"
        Then I expect that element "tbody" contains the text "Dog status set to Failed to exempt dog"
        And I expect that element "tbody" contains the text "Non-compliance letter sent"

    Scenario: Add CDO issued, CDO expiry and court to dog in interim exempt status(update status from interim exempt to pre-exempt) 
        Given I open the url "/"
        When I click on the link "Search dog index"
        And I set "Maxie" to the inputfield "#searchTerms"
        And I press "Enter"
        And I click on the link containing "ED30"
        And I click on the element "(//a[contains(text(),'Edit details')])[2]"
        And I set "11" to the inputfield "#cdoIssued-day"
        And I set "03" to the inputfield "#cdoIssued-month"
        And I set "2024" to the inputfield "#cdoIssued-year"
        And I set "11" to the inputfield "#cdoExpiry-day"
        And I set "05" to the inputfield "#cdoExpiry-month"
        And I set "2024" to the inputfield "#cdoExpiry-year"
        And I clear the inputfield "#court"
        And I set "Barnsley Law Courts" to the inputfield "#court"
        And I click on the element "#legislationOfficer"
        And I click on the element "button=Save details"
        And I click on the link "Dog record" 
        Then I expect that element "h1" contains the text "Dog ED30"
        And I expect that element "(//dd)[14]" contains the text "Applying for exemption"

    Scenario: Check the activity for dog
        When I click on the link "Check activity"
        Then I expect that element "tbody" contains the text "Dog status set to Applying for exemption"
        And I expect that element "tbody" contains the text "CDO issue date updated"
        And I expect that element "tbody" contains the text "CDO expiry date updated"

    Scenario: Add First certificate issued and Insurance renewal date to dog in pre-exempt status(update pre-exempt to Exempt) 
        Given I open the url "/"
        When I click on the link "Search dog index"
        And I set "Bruce" to the inputfield "#searchTerms"
        And I press "Enter"
        And I click on the link containing "ED30"
        And I click on the link "Dog record"
        And I click on the element "(//a[contains(text(),'Edit details')])[2]"
        And I set "15" to the inputfield "#certificateIssued-day"
        And I set "03" to the inputfield "#certificateIssued-month"
        And I set "2024" to the inputfield "#certificateIssued-year"
        And I set "11" to the inputfield "#insuranceRenewal-day"
        And I set "03" to the inputfield "#insuranceRenewal-month"
        And I set "2026" to the inputfield "#insuranceRenewal-year"
        And I select the option with the value "Dogs Trust" for element "#insuranceCompany"
        And I click on the element "button=Save details" 
        Then I expect that element "h1" contains the text "Dog ED30"
        And I expect that element "(//dd)[15]" contains the text "Exempt"

    Scenario: Check the activity for dog
        When I click on the link "Check activity"
        Then I expect that element "tbody" contains the text "Dog status set to Exempt"
        And I expect that element "tbody" contains the text "Last known insurance renewal date updated"
        And I expect that element "tbody" contains the text "Insurance company updated"
        And I expect that element "tbody" contains the text "First certificate date updated"

    Scenario: Add dog date of death to dog in Exempt status(update Exempt to Inactive) 
        Given I open the url "/"
        When I click on the link "Search dog index"
        And I set "Bruce" to the inputfield "#searchTerms"
        And I press "Enter"
        And I click on the link containing "ED30"
        And I click on the element "(//a[contains(text(),'Edit details')])[1]"
        And I set "15" to the inputfield "#dateOfDeath-day"
        And I set "03" to the inputfield "#dateOfDeath-month"
        And I set "2024" to the inputfield "#dateOfDeath-year"
        And I click on the element "button=Save details" 
        Then I expect that element "h1" contains the text "Dog ED30"
        And I expect that element "(//dd)[16]" contains the text "Dog dead"

    Scenario: Check the activity for dog
        When I click on the link "Check activity"
        Then I expect that element "tbody" contains the text "Dog status set to Dog dead"
        And I expect that element "tbody" contains the text "Dog date of death added"