Feature: Update dogs Inactive sub-statuses(Dog Dead, Dog Exported, Reported Stolen and Owner untreaceable)

    Scenario: Add dogs and update statuses
        Given I open the url "/"
        When I click on the link containing "Process new CDO or"
        And I set "Canary" to the inputfield "#firstName"
        And I set "Bush" to the inputfield "#lastName"
        And I click on the element "button=Continue"
        And I set "BN3 7EL" to the inputfield "#postcode"
        And I set "11" to the inputfield "#houseNumber"
        And I click on the element "button=Continue"
        And I click on the element "button=Confirm address"
        And I set "563214789563256" to the inputfield "#microchipNumber"
        And I click on the element "button=Continue"
        And I select the radio option with the value "XL Bully" from the radio group "breed"
        And I set "Polo" to the inputfield "#name"
        And I select the radio option with the value "cdo" from the radio group "applicationType"
        And I set "15" to the inputfield "#cdoIssued-day"
        And I set "10" to the inputfield "#cdoIssued-month"
        And I set "2024" to the inputfield "#cdoIssued-year"
        And I click on the element "button=Add dog details"
        And I click on the element "button=Add another dog for this owner"
        And I set "896325462315793" to the inputfield "#microchipNumber"
        And I click on the element "button=Continue"
        And I select the radio option with the value "Pit Bull Terrier" from the radio group "breed"
        And I set "Raha" to the inputfield "#name"
        And I select the radio option with the value "cdo" from the radio group "applicationType"
        And I set "14" to the inputfield "#cdoIssued-day"
        And I set "10" to the inputfield "#cdoIssued-month"
        And I set "2024" to the inputfield "#cdoIssued-year"
        And I click on the element "button=Add dog details"
        And I click on the element "button=Add another dog for this owner"
        And I set "147896547859687" to the inputfield "#microchipNumber"
        And I click on the element "button=Continue"
        And I select the radio option with the value "Japanese Tosa" from the radio group "breed"
        And I set "Molly" to the inputfield "#name"
        And I select the radio option with the value "cdo" from the radio group "applicationType"
        And I set "14" to the inputfield "#cdoIssued-day"
        And I set "10" to the inputfield "#cdoIssued-month"
        And I set "2024" to the inputfield "#cdoIssued-year"
        And I click on the element "button=Add dog details"
        And I click on the element "button=Add another dog for this owner"
        And I set "569874123569815" to the inputfield "#microchipNumber"
        And I click on the element "button=Continue"
        And I select the radio option with the value "Dogo Argentino" from the radio group "breed"
        And I set "Happy" to the inputfield "#name"
        And I select the radio option with the value "interim-exemption" from the radio group "applicationType"
        And I click on the element "button=Add dog details"
        And I click on the element "button=Confirm details"
        And I set "Birmingham Magistrates Court at the Victoria Law Courts" to the inputfield "#court"
        And I click on the element "#legislationOfficer"
        And I click on the element "button=Continue"
        And I click on the element "button=Confirm details"
        And I click on the link "Home"
        And I click on the link "Search dog index"
        And I set "Molly" to the inputfield "#searchTerms"
        And I press "Enter"
        And I click on the link containing "ED30"
        And I click on the link "Send application pack"
        And I click on the element "#taskDone"
        And I click on the element "button=Save and continue"
        And I click on the link "Process application"
        And I click on the element "#taskDone"
        And I click on the element "button=Save and continue"
        And I click on the link "Record insurance details"
        And I select the option with the value "Dogs Trust" for element "#insuranceCompany"
        And I set "10" to the inputfield "#insuranceRenewal-day"
        And I set "03" to the inputfield "#insuranceRenewal-month"
        And I set "2026" to the inputfield "#insuranceRenewal-year"
        And I click on the element "button=Save and continue"
        And I click on the link "Record application fee payment"
        And I set "10" to the inputfield "#applicationFeePaid-day"
        And I set "07" to the inputfield "#applicationFeePaid-month"
        And I set "2024" to the inputfield "#applicationFeePaid-year"
        And I click on the element "button=Save and continue"
        And I click on the link "Request Form 2"
        And I click on the element "#taskDone"
        And I click on the element "button=Save and continue"
        And I click on the link "Record the verification date for microchip and neutering"
        And I set "11" to the inputfield "#microchipVerification-day"
        And I set "09" to the inputfield "#microchipVerification-month"
        And I set "2024" to the inputfield "#microchipVerification-year"
        And I set "11" to the inputfield "#neuteringConfirmation-day"
        And I set "09" to the inputfield "#neuteringConfirmation-month"
        And I set "2024" to the inputfield "#neuteringConfirmation-year"
        And I click on the element "button=Save and continue"
        And I click on the link "Continue"
        And I click on the element "button=Generate certificate"

    Scenario: Add dateOfDeath, dateExported, dateStolen and dateUntraceable to dog in 'Applying for exemption' status
        When I open the url "/"
        And I click on the link "Search dog index"
        And I set "Polo" to the inputfield "#searchTerms"
        And I press "Enter"
        And I click on the link containing "ED30"
        And I click on the link "Dog record"
        And I click on the element "(//a[contains(text(),'Edit details')])[1]"
        And I set "5" to the inputfield "#dateOfDeath-day"
        And I set "10" to the inputfield "#dateOfDeath-month"
        And I set "2024" to the inputfield "#dateOfDeath-year"
        And I set "1" to the inputfield "#dateExported-day"
        And I set "10" to the inputfield "#dateExported-month"
        And I set "2024" to the inputfield "#dateExported-year"
        And I set "2" to the inputfield "#dateStolen-day"
        And I set "10" to the inputfield "#dateStolen-month"
        And I set "2024" to the inputfield "#dateStolen-year"
        And I set "4" to the inputfield "#dateUntraceable-day"
        And I set "10" to the inputfield "#dateUntraceable-month"
        And I set "2024" to the inputfield "#dateUntraceable-year"
        And I click on the element "button=Save details"
        Then I expect that element "(//dd)[18]" contains the text "Dog dead"

    Scenario: Check the history for the dog
        When I click on the link "Check history"
        Then I expect that element "tbody" contains the text "Dog status set to Dog dead"
        And I expect that element "tbody" contains the text "Date untraceable added"
        And I expect that element "tbody" contains the text "Date stolen added"
        And I expect that element "tbody" contains the text "Date exported added"
        And I expect that element "tbody" contains the text "Dog date of death added"
        And I expect that element "tbody" contains the text "Dog record created (Applying for exemption)"

    Scenario: Add dateExported, dateStolen and dateUntraceable to dog in Interim exemption status
        Given I open the url "/"
        And I click on the link "Search dog index"
        And I set "Happy" to the inputfield "#searchTerms"
        And I press "Enter"
        And I click on the link containing "ED30"
        And I click on the element "(//a[contains(text(),'Edit details')])[1]"
        And I set "1" to the inputfield "#dateExported-day"
        And I set "10" to the inputfield "#dateExported-month"
        And I set "2024" to the inputfield "#dateExported-year"
        And I set "2" to the inputfield "#dateStolen-day"
        And I set "10" to the inputfield "#dateStolen-month"
        And I set "2024" to the inputfield "#dateStolen-year"
        And I set "4" to the inputfield "#dateUntraceable-day"
        And I set "10" to the inputfield "#dateUntraceable-month"
        And I set "2024" to the inputfield "#dateUntraceable-year"
        And I click on the element "button=Save details"
        Then I expect that element "(//dd)[17]" contains the text "Dog exported"

    Scenario: Check the history for the dog
        When I click on the link "Check history"
        Then I expect that element "tbody" contains the text "Dog status set to Dog exported"
        And I expect that element "tbody" contains the text "Date untraceable added"
        And I expect that element "tbody" contains the text "Date stolen added"
        And I expect that element "tbody" contains the text "Date exported added"
        And I expect that element "tbody" contains the text "Dog record created (Interim exempt)"

    Scenario: Add dateStolen and dateUntraceable to dog in Exempt status
        Given I open the url "/"
        And I click on the link "Search dog index"
        And I set "Molly" to the inputfield "#searchTerms"
        And I press "Enter"
        And I click on the link containing "ED30"
        And I click on the element "(//a[contains(text(),'Edit details')])[1]"
        And I set "2" to the inputfield "#dateStolen-day"
        And I set "10" to the inputfield "#dateStolen-month"
        And I set "2024" to the inputfield "#dateStolen-year"
        And I set "4" to the inputfield "#dateUntraceable-day"
        And I set "10" to the inputfield "#dateUntraceable-month"
        And I set "2024" to the inputfield "#dateUntraceable-year"
        And I click on the element "button=Save details"
        Then I expect that element "(//dd)[16]" contains the text "Reported stolen"

    Scenario: Check the history for the dog
        When I click on the link "Check history"
        Then I expect that element "tbody" contains the text "Dog status set to Reported stolen"
        And I expect that element "tbody" contains the text "Date untraceable added"
        And I expect that element "tbody" contains the text "Date stolen added"
        And I expect that element "tbody" contains the text "Dog status set to Exempt"
        And I expect that element "tbody" contains the text "Dog record created (Applying for exemption)"

     Scenario: Add dateUntraceable to dog in Applying for exemption status
        Given I open the url "/"
        And I click on the link "Search dog index"
        And I set "Raha" to the inputfield "#searchTerms"
        And I press "Enter"
        And I click on the link containing "ED30"
        And I click on the link "Dog record"
        And I click on the element "(//a[contains(text(),'Edit details')])[1]"
        And I set "4" to the inputfield "#dateUntraceable-day"
        And I set "10" to the inputfield "#dateUntraceable-month"
        And I set "2024" to the inputfield "#dateUntraceable-year"
        And I click on the element "button=Save details"
        Then I expect that element "(//dd)[15]" contains the text "Owner untraceable"  

    Scenario: Check the history for the dog
        When I click on the link "Check history"
        Then I expect that element "tbody" contains the text "Dog status set to Owner untraceable"
        And I expect that element "tbody" contains the text "Date untraceable added"
        And I expect that element "tbody" contains the text "Dog record created (Applying for exemption)"