Feature: View Dog details and check history

        Scenario: Navigate to Enforcement Search page
                Given I open the url "/"
                When I click on the element "button=Accept analytics cookies"
                And I click on the element "button=Hide this message"
                And I click on the link "Start now"
                Then I expect that element "h1" contains the text "Search"

        Scenario: Search dog in national records
                When I select the radio option with the value "true" from the radio group "national"
                And I set "bravo" to the inputfield "#searchTerms"
                And I press "Enter"
                Then I expect that element "html" contains the text "1 record found."

        Scenario: View dog details
                When I click on the link containing "ED30"
                Then I expect that element "h1" contains the text "Dog ED30"
                And I expect that element "(//dd)[1]" contains the text "Bravo"
                And I expect that element "(//dd)[2]" contains the text "Pit Bull Terrier"
                And I expect that element "(//dd)[3]" contains the text "White"
                And I expect that element "(//dd)[4]" contains the text "Male"
                And I expect that element "(//dd)[5]" contains the text "01 February 2022"   
                And I expect that element "(//dd)[6]" contains the text "RG4587GH" 
                And I expect that element "(//dd)[7]" contains the text "852638526311111" 
                And I expect that element "(//dd)[8]" contains the text "852638526322222"
                And I expect that element "(//dd)[9]" contains the text "Mike Turner"
                And I expect that element "(//dd)[10]" contains the text "03 March 1990"
                And I expect that element "(//dd)[11]" contains the text "6 HEATH MEAD"
                And I expect that element "(//dd)[11]" contains the text "CANTON"
                And I expect that element "(//dd)[11]" contains the text "CARDIFF" 
                And I expect that element "(//dd)[11]" contains the text "CF14 3PJ"
                And I expect that element "(//dd)[13]" contains the text "mike1_turner1@outlook.com"
                And I expect that element "(//dd)[14]" contains the text "01604 785856"   
                And I expect that element "(//dd)[15]" contains the text "07566874546" 
                And I expect that element "(//dd)[16]" contains the text "Wales"
                And I expect that element "(//dd)[17]" contains the text "Exempt"
                And I expect that element "(//dd)[19]" contains the text "10 February 2024"
                And I expect that element "(//dd)[20]" contains the text "2015"
                And I expect that element "(//dd)[21]" contains the text "01 February 2024"
                And I expect that element "(//dd)[22]" contains the text "01 April 2024"
                And I expect that element "(//dd)[23]" contains the text "Northampton (Northampton Crown Court)"
                And I expect that element "(//dd)[24]" contains the text "South Wales Police"
                And I expect that element "(//dd)[25]" contains the text "Declan"
                And I expect that element "(//dd)[26]" contains the text "10 March 2024"
                And I expect that element "(//dd)[27]" contains the text "Dogs Trust"
                And I expect that element "(//dd)[28]" contains the text "10 March 2026"
                And I expect that element "(//dd)[29]" contains the text "10 March 2023"
                And I expect that element "(//dd)[30]" contains the text "11 March 2023"
                And I expect that element "(//dd)[31]" contains the text "11 March 2023"

        Scenario: Check the history for the dog 
                When I click on the link "Check and download history"
                Then I expect that element "tbody" contains the text "Dog record created (Applying for exemption)"
                And I expect that element "tbody" contains the text "Microchip number 1 updated"
                And I expect that element "tbody" contains the text "Microchip number 2 updated"
                And I expect that element "tbody" contains the text "Tattoo updated"
                And I expect that element "tbody" contains the text "Dog date of birth updated"
                And I expect that element "tbody" contains the text "Sex updated"
                And I expect that element "tbody" contains the text "Dog colour updated"
                And I expect that element "tbody" contains the text "Dog status set to Exempt"
                And I expect that element "tbody" contains the text "Police force updated"
                And I expect that element "tbody" contains the text "Owner date of birth updated"

        Scenario: download the history of the dog
                When I click on the link "Download the record"
                Then I expect that element "h1" contains the text "View and download the record for Dog"